ifeq ($(obj),)
obj := .
endif

DEPTH := ../..

include $(obj)/$(DEPTH)/os/linux/Makefile-linux.common

INCS += -I$(HAL) -I$(HAL)/$(OS) -I$(ATH) -I$(ATH_RATE) -I$(ATH_PKTLOG)

INCS += -I$(obj)/$(DEPTH)/umac/include -I$(obj)/$(DEPTH)/umac/if_lmac

obj-m += ath_pktlog.o

EXTRA_CFLAGS+= $(INCS) $(COPTS)
ath_pktlog-objs := pktlog.o linux.o

clean-files := modules.order
