// Copyright (c) 2012 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _TX_FLUSH_REQ_H_
#define _TX_FLUSH_REQ_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//	0	flush_req_reason[7:0], reserved_0a[31:8]
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_TX_FLUSH_REQ 1

struct tx_flush_req {
    volatile uint32_t flush_req_reason                :  8, //[7:0]
                      reserved_0a                     : 24; //[31:8]
};

/*

flush_req_reason
			
			The reason why the flush request was generated.
			
			Reason codes: [TBD]
			
			<legal all>

reserved_0a
			
			<legal 0>
*/


/* Description		TX_FLUSH_REQ_0_FLUSH_REQ_REASON
			
			The reason why the flush request was generated.
			
			Reason codes: [TBD]
			
			<legal all>
*/
#define TX_FLUSH_REQ_0_FLUSH_REQ_REASON_OFFSET                       0x00000000
#define TX_FLUSH_REQ_0_FLUSH_REQ_REASON_LSB                          0
#define TX_FLUSH_REQ_0_FLUSH_REQ_REASON_MASK                         0x000000ff

/* Description		TX_FLUSH_REQ_0_RESERVED_0A
			
			<legal 0>
*/
#define TX_FLUSH_REQ_0_RESERVED_0A_OFFSET                            0x00000000
#define TX_FLUSH_REQ_0_RESERVED_0A_LSB                               8
#define TX_FLUSH_REQ_0_RESERVED_0A_MASK                              0xffffff00


#endif // _TX_FLUSH_REQ_H_
