extern A_INT16 Ar9287_LengthGet(int iBand);
extern A_INT16 Ar9287_ChecksumGet(void);
extern A_INT16 Ar9287_EepromVersionGet(void);
extern A_INT32 Ar9287templateVersion(int value);
extern int Ar9287_OpFlagsGet(void);
extern int Ar9287_eepMiscGet(void);
extern int Ar9287_RegDmnGet(int *value, int ix, int *num);
extern A_INT32 Ar9287_MacAdressGet(A_UINT8 *mac);
extern int Ar9287_TxRxMaskGet(void);
extern int Ar9287_RxMaskGet(void);
extern int Ar9287_TxMaskGet(void);
extern int Ar9287_RFSilentGet(void);
extern int Ar9287_BlueToothOptionsGet(void);
extern int Ar9287_DeviceCapGet(void);
extern int Ar9287_CalibrationBinaryVersionGet(void);
extern int Ar9287_DeviceTypeGet(void);
extern int Ar9287_OpenLoopPwrCntlGet(void);
extern int Ar9287_PwrTableOffsetSetGet(void);
extern int Ar9287_TempSensSlopeGet(void);
extern int Ar9287_TempSensSlopePalOnGet(void);
extern int Ar9287_FutureBaseGet(int *value, int ix, int *num);
extern A_INT32 Ar9287_CustomerDataGet(A_UCHAR *data, A_INT32 len);
extern int Ar9287_TemplateVersionGet(void);
extern int Ar9287_AntCtrlChainGet(int *value, int ix, int *num);
extern int Ar9287_AntCtrlCommonGet(int iBand);
extern int Ar9287_AntennaGainGet(int *value, int ix, int *num);
extern int Ar9287_SwitchSettlingGet(int iBand);
extern A_INT32 Ar9287_TxRxAttenChGet(int *value, int ix, int *num);
extern A_INT32 Ar9287_RxTxMarginChGet(int *value, int ix, int *num);
extern int Ar9287_AdcDesiredSizeGet(int iBand);
extern int Ar9287_TxEndToXpaOffGet(int iBand);
extern int Ar9287_TxEndToRxOnGet(int iBand);
extern int Ar9287_TxFrameToXpaOnGet(int iBand);
extern int Ar9287_Thresh62Get(int iBand);
extern int Ar9287_NoiseFloorThreshChGet(int *value, int ix, int *num);
extern int Ar9287_XpdGainGet(int iBand);
extern int Ar9287_XpdGet(int iBand);
extern int Ar9287_IQCalIChGet(int *value, int ix, int *num);
extern int Ar9287_IQCalQChGet(int *value, int ix, int *num);
extern A_INT32 Ar9287_PdGainOverlapGet(int iBand);	
extern int Ar9287_XpaBiasLvlGet(int iBand);
extern int Ar9287_TxFrameToDataStartGet(int iBand);
extern int Ar9287_TxFrameToPaOnGet(int iBand);
extern 	A_INT32 Ar9287_HT40PowerIncForPdadcGet(int iBand);
extern A_INT32 Ar9287_BswAttenGet(int *value, int ix, int *num);
extern A_INT32 Ar9287_BswMarginGet(int *value, int ix, int *num);
extern A_INT32 Ar9287_SwSettleHT40Get(int iBand);
extern A_INT32 Ar9287_ModalHeaderVersionGet(int iBand);
extern A_INT32 Ar9287_db1Get(int iBand);
extern A_INT32 Ar9287_db2Get(int iBand);
extern A_INT32 Ar9287_ob_cckGet(int iBand);
extern 	A_INT32 Ar9287_ob_pskGet(int iBand);
extern A_INT32 Ar9287_ob_qamGet(int iBand);
extern A_INT32 Ar9287_ob_pal_offGet(int iBand);
extern int Ar9287_FutureModalGet(int *value, int ix, int *num);
extern int Ar9287_PaddingGet(int iBand);
extern A_INT32 Ar9287_SpurChansGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_SpurRangeLowGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_SpurRangeHighGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_SpurRangeGet(int *sValue[], int iBand);
extern A_INT32 Ar9287_CalPierFreqGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrcckGet(double *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrGet(double *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrht20Get(double *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrht40Get(double *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrcckChannelGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrChannelGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrht20ChannelGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalTGTpwrht40ChannelGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CtlIndexGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CtlChannelGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CtlPowerGet(double *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CtlFlagGet(int *value, int ix, int iy, int iz, int *num, int iBand);
//extern void ar9287_eepromDump(int client, ar9287_eeprom_t *pEepStruct);
extern int Ar9287_PrintEepromStruct(int client);
extern A_INT32 Ar9287_CalPierOpenPowerGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalPierOpenVoltMeasGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CalPierOpenPcdacGet(int *value, int ix, int iy, int iz, int *num, int iBand);
extern A_INT32 Ar9287_CaldataMemoryTypeGet(A_UCHAR *memType, A_INT32 maxlength);
