ifeq ($(obj),)
obj := .
endif

DEPTH := ../..

include $(obj)/$(DEPTH)/os/linux/Makefile-linux.common

INCS += -I$(HAL) -I$(HAL)/$(OS) -I$(ATH) -I$(ATH_RATE) -I$(ATH_PKTLOG) -I$(WLAN) -I$(IF_WLAN) -I$(ATH_DFS) -I$(ATH_SPECTRAL) -I$(ATHEROSPATH) -I$(obj)/$(DEPTH)/../../apps/spectral/common

obj-m += ath_spectral.o

EXTRA_CFLAGS+= $(INCS) $(COPTS) -DATH_SUPPORT_SPECTRAL=1 -DSPECTRAL_USE_NETLINK_SOCKETS=1

ath_spectral-objs := spectral.o spectral_netlink.o spectral_cmds.o spectral_process_data.o spectral_phyerr.o
