// Copyright (c) 2012 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _TX_CBF_OFFSET_H_
#define _TX_CBF_OFFSET_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//	0	cbf_hdr_offset[7:0], reserved[31:8]
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_TX_CBF_OFFSET 1

struct tx_cbf_offset {
    volatile uint32_t cbf_hdr_offset                  :  8, //[7:0]
                      reserved                        : 24; //[31:8]
};

/*

cbf_hdr_offset
			
			This field defines the start location of the CV data
			within a CBF packet.  <legal 24, 30> ### James verify ####

reserved
			
			Reserved - MAC to set this field to 0, PHY to ignore
			this field. <legal 0>
*/


/* Description		TX_CBF_OFFSET_0_CBF_HDR_OFFSET
			
			This field defines the start location of the CV data
			within a CBF packet.  <legal 24, 30> ### James verify ####
*/
#define TX_CBF_OFFSET_0_CBF_HDR_OFFSET_OFFSET                        0x00000000
#define TX_CBF_OFFSET_0_CBF_HDR_OFFSET_LSB                           0
#define TX_CBF_OFFSET_0_CBF_HDR_OFFSET_MASK                          0x000000ff

/* Description		TX_CBF_OFFSET_0_RESERVED
			
			Reserved - MAC to set this field to 0, PHY to ignore
			this field. <legal 0>
*/
#define TX_CBF_OFFSET_0_RESERVED_OFFSET                              0x00000000
#define TX_CBF_OFFSET_0_RESERVED_LSB                                 8
#define TX_CBF_OFFSET_0_RESERVED_MASK                                0xffffff00


#endif // _TX_CBF_OFFSET_H_
