#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

QTN_TARGET_IP="$CONFIG_PACKAGE_QUANTENNA_RGMII_TARGET_IP"
QTN_IF="0"

find_qtn_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   qtn_dev=`/usr/sbin/status_oper GET "QCA_MAP" "$CPEID"`
   QTN_IF=${qtn_dev:4}
   #echo "QTN $QTN_IF "
}

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then

    UP_STATUS=`call_qcsapi_sockrpc --host ${QTN_TARGET_IP} rfstatus wifi${QTN_IF}` 
    if [ "${UP_STATUS}" = "On" ]; then
        status=1
    else
        status=0
    fi
        
    BW_VALUE=`call_qcsapi_sockrpc --host ${QTN_TARGET_IP} get_bw wifi${QTN_IF}`
    if [ "${BW_VALUE}" = "20" ]; then
       BW=0
    elif [ "${BW_VALUE}" = "40" ]; then
       BW=1
    else
       BW=2
    fi
    GI_STATUS=`call_qcsapi_sockrpc --host ${QTN_TARGET_IP} get_option wifi${QTN_IF} short_GI`
    if [ "${GI_STATUS}" = "TRUE" ]; then
       GI=0
    else
       GI=1
    fi

    channel=`call_qcsapi_sockrpc --host ${QTN_TARGET_IP} get_channel wifi${QTN_IF}`
 
    echo "status=\"$status\""
    echo "channelsInUse=\"\""
    echo "channel=\"$channel\""
    echo "chanWidth=\"$BW\""
    echo "guardIntvl=\"$GI\""
    echo "MCS=\"\""
fi
