#!/bin/sh

if [ ! "$ENVLOADED" ]; then
   if [ -r /etc/rc.conf ]; then
       . /etc/rc.conf 2> /dev/null
      ENVLOADED="1"
   fi
fi

if [ ! "$CONFIGLOADED" ]; then
   if [ -r /etc/rc.d/config.sh ]; then
      . /etc/rc.d/config.sh 2>/dev/null
      CONFIGLOADED="1"
   fi
fi


if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then # [
    ##
    ## Get the name of the bridge. WE ARE ASSUMING ONLY ONE FOR NOW
    ##

#    BRNAME=`brctl show | grep -v bridge | cut -b 1-4`

    ##
    ## Check for a kill all
    ##
#    VAPLIST=`iwconfig | grep ath | cut -b 1-4`

#    if [ "${VAPLIST}" != "" ]; then

        #
        # Do the same for all instances of hostapd, wpa_supplicant, and wsc
        #

#        HOSTAPDLIST=`ps | grep /sbin/hostapd | cut -b 1-5`
#        if [ "${HOSTAPDLIST}" != "" ]; then
#            for i in $HOSTAPDLIST ; do
#                echo "killing $i"
#                kill -9 $i
#            done
#        fi

#        SUPPLIST=`ps | grep wpa_supplicant | cut -b 1-5`
#        if [ "${SUPPLIST}" != "" ]; then
#            for i in $SUPPLIST ; do
#                echo "killing $i"
#                 kill -9 $i
#             done
#        fi
#		sleep 4

#        for i in $VAPLIST
#        do

#            brctl delif $BRNAME $i

            #
            # Bring the interface down
            #
#            ifconfig $i down
#        done

#        for i in $VAPLIST
#        do
#            echo "killing $i"
#            wlanconfig $i destroy
#        done
#    fi
    
    #
    # Unload all modules
    #
#    rmmod ath_pktlog
#    sleep 1
#    rmmod umac
#    sleep 1
#    rmmod ath_dev
#    rmmod ath_dfs
#    rmmod ath_rate_atheros
#    rmmod ath_hal
#    sleep 1
#    rmmod ath_htc_hst
#    rmmod ath_hif_usb
#    sleep 1
#    rmmod asf
#    rmmod adf

    #
    # Remove files in /tmp
    #
    
#    rm -rf /tmp/br*
#    rm -rf /tmp/ap*
#    rm -rf /tmp/sta*
#    rm -rf /tmp/top*
fi # ]
