#!/bin/sh

if [ ! "$ENVLOADED" ]; then
   if [ -r /etc/rc.conf ]; then
       . /etc/rc.conf 2> /dev/null
      ENVLOADED="1"
   fi
fi

if [ ! "$CONFIGLOADED" ]; then
   if [ -r /etc/rc.d/config.sh ]; then
      . /etc/rc.d/config.sh 2>/dev/null
      CONFIGLOADED="1"
   fi
fi

#ATH_IF=""
#find_ath_if_from_index() {
#   eval CPEID='$'wlmn_${1}'_cpeId'
#   if [ "$CPEID" = "" ]; then
#      echo "Not matched"
#      exit
#   fi
#   ath_dev=`/usr/sbin/status_oper GET "ATH_MAP" "$CPEID"`
#   ATH_IF=${ath_dev:3}
#   #echo "ATH_IF $ATH_IF "
#}

echo "qtn_wlan_ap_stop $@"
#if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then # [
#    find_ath_if_from_index $1
#    eval APNAME=ath${ATH_IF}
#
#  un registering interface with PPA
#    ppacmd dellan -i ${APNAME}
#    iwpriv ${APNAME} ppa 0
#    ifconfig ${APNAME} down
#    #wlanconfig ${APNAME} destroy
#fi # ]
