#!/bin/sh

WLMN_INDEX=1

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
    eval APENABLE='$'wlmn_${WLMN_INDEX}_apEnable
    ######################################################
    # AP Enable
    ######################################################
    if [ "${APENABLE}" = "1" ]; then
	# No kernel module is required for QTN RGMII module
	# Power on QTN module can be implemented here
	if [ "$CONFIG_PACKAGE_QUANTENNA_FIRMWARE_EMBEDDED" = "1" ]; then
        # Copy firmware to tftp folder. QTN target will download it then boots up
        # By default, IP of QTN RGMII target is 1.1.1.2, IP of host server is 1.1.1.1
        # Configuration eth port is needed (should move to swich configuration script later)
           cp /lib/firmware/u-boot.bin /ramdisk/tftp_upload/
           cp /lib/firmware/topaz-linux.lzma.img /ramdisk/tftp_upload/
	   if [ "$lan_port_sep_enable" = "1" ]; then
		ifconfig eth0.2 1.1.1.1
	   else
		ifconfig eth0 1.1.1.1
	   fi
	fi
        echo "Initialize QTN module(RGMII)"
    else
        echo "AP is not enabled"
        exit
    fi

fi
