ifeq ($(obj),)
obj := .
endif

DEPTH := ../..

include $(obj)/$(DEPTH)/os/linux/Makefile-linux.common

INCS += -I$(HAL) -I$(HAL)/$(OS) -I$(obj)/inc -I$(ATH) -I$(ATH_RATE) -I$(ATH_DFS) -I$(WLAN) -I$(IF_WLAN) -I${ADF_ADF_INC} -I${ADF_LNX_OS_INC} -I${ADF_LNX_NBUF_INC} -I${ADF_LNX_INC} -I${ADF_LNX_NET_INC} -I$(obj)/$(DEPTH)/adf/net/$(OS) -I${TX99}

obj-m += hst_tx99.o

EXTRA_CFLAGS+= $(INCS) $(COPTS)


hst_tx99-objs := ath_tx99.o

ifneq ($(strip ${ATH_SUPPORT_HTC}),1)
hst_tx99-objs += ath_tx99_tgt.o
endif
