#!/bin/sh
##
## Compatability scripts for older versions
##
. /etc/ath/apcfg

if [ -d /etc/ath ] ; then
        export PATH=$PATH:/etc/ath
fi


WPS_LED_OFF=1
echo $WPS_LED_OFF  > /proc/simple_config/simple_config_led  

KER_VER_31=`set | uname -a | grep -c "2.6.31"`
if [ "${KER_VER_31}" = 1 ]; then
    pktlogconf -d wifi0
    pktlogconf -d wifi1
fi


killVAP all
#Finally, unload all modules
sleep 3
if [ "${AP_CONF_ACFG}"  -eq "1" ]; then
	prepareACFG unload
fi
#/etc/rc.d/rc.wlan down
rm -f /tmp/.apup
