ifeq ($(obj),)
obj := .
endif

DEPTH := ..

#
# Path to the Atheros driver framework source base
#
ADF := $(src)/../adf

#
# Path to the Atheros service framework source base
#
ASF := $(src)

include $(obj)/$(DEPTH)/os/linux/Makefile-linux.common

ifeq ($(ATH_SUPPORT_HTC),1)
INCS = -include $(COMINC)/compat.h -I$(COMINC) -I$(WLAN_TOP)/os/$(OS)/include -I$(WLAN_TOP)/os/$(OS)/src -I$(KERNELPATH)/include
INCS += -I$(WLAN_TOP)/asf/include
INCS +=                            \
    -I$(WLAN_TOP)/adf/include/os   \
    -I$(WLAN_TOP)/adf/include/net  \
    -I$(WLAN_TOP)/adf/include/nbuf
INCS +=                            \
    -I$(WLAN_TOP)/adf/os/$(OS)     \
    -I$(WLAN_TOP)/adf/net/$(OS)    \
    -I$(WLAN_TOP)/adf/nbuf/$(OS)
endif

INCS += -I$(ASF)/include -I$(ADF)/include/os -I$(ADF)/os/linux
obj-m += asf.o

EXTRA_CFLAGS+= $(INCS) $(COPTS) -Wno-unused-function

asf-objs := asf_print.o asf_amem.o linux/asf_module.o

clean-files := modules.order
